### ISSUE TITLE
add, edit and delete groups and memberships

### ISSUE THREAD

**Issue by xsd08tfu** [xsd08tfu/sw-bug-tracker#10]
Copy the way we administer teams for this, it works well. Also, when a group is deleted, you need to delete corresponding memberships!

**Comment by xsd08tfu** [comment]
Memberships are done. It’s just managing the groups now.

**Comment by benjalon** [comment]
Could you clarify this one please, I'm not sure exactly what method I'm copying.

**Comment by xsd08tfu** [comment]
Hi Ben, for this one you are copying the way of adding Teams to the system.
