### ISSUE TITLE
Editing workers manually - returning to the previous screen

### ISSUE THREAD

**Issue by hxc08vwu** [xsd08tfu/sw-bug-tracker#111]
## Describe the bug ##
When you have edited a worker, you click submit and if you click the back button you are taken to the start (so, students starting with the letter A) - I'm trying to edit students with the starting letter R...it's annoying me :-) 
**To Reproduce**
1. Go to '...'https://studentworkers.uea.ac.uk/workers/list.php
2. Click on '....' A worker, edit them, press submit
Click "back" and you're taken back to the start (nooooo)

## Expected behavior ##
I want to be taken back to the page I am on at the moment...which is currently page 24

**Screenshots**

**Comment by xsd08tfu** [comment]
Worker editing will be in a modal in new workers world.

**Comment by xsd08tfu** [comment]
xsd08tfu/digital-sign-in#158
