### ISSUE TITLE
OOP Events

### ISSUE THREAD

**Issue by benjalon** [xsd08tfu/sw-bug-tracker#115]
I doubt this will be a big enough priority for a long time but maybe events could be converted to OOP. 
This would simplify the system a bit more and I don't think it'd take too long!

**Comment by benjalon** [comment]
Might tie in with event end date.

**Comment by xsd08tfu** [comment]
Items needed:
- [ ] Event end date/time
- [ ] Event Category
- [ ] Allow for separate events and jobs
- [ ] Which team owns event
- [ ] Budget Holder
- [ ] Everything we already know!
- [ ] Be extendable.

**Comment by benjalon** [comment]
when you say budget holder do you mean a person or somewhere to keep track of money?
