### ISSUE TITLE
Pre filling options when creating a worker

### ISSUE THREAD

**Issue by hxc08vwu** [xsd08tfu/sw-bug-tracker#121]
## Describe the bug ##
Can we get rid of the pre filling options when creating a worker? It gives you options to select an email address, payroll number, student number, mobile etc. that you've already entered. For GDPR reasons I think we need to make sure we don't have this!

**Comment by benjalon** [comment]
I think its the browser that stores this info so maybe turn the feature off there. There might be a way to code it but the sites I've been looking at say its difficult and often doesn't work.

**Comment by xsd08tfu** [comment]
I think you can just use autocomplete="off", can you not?

**Comment by benjalon** [comment]
Browsers just ignore it unfortunately.

**Comment by xsd08tfu** [comment]
How strange.. I think Safari is more respecting of autofill.....
