### ISSUE TITLE
Flagging that there are duplicate entries in certain fields

### ISSUE THREAD

**Issue by hxc08vwu** [xsd08tfu/sw-bug-tracker#127]
## Describe the bug ##
Just a thought...what if some student enters their UEA email address incorrectly...like if I'm Caroline.Stewart@uea.ac.uk but I put C.Stewart@uea.ac.uk because I'm an idiot, what if another user like Charles Stewart has the C.Stewart email address? But because I've put it in...it's wrong...

Can we make sure duplicate student number, UEA email address and mobile number flags an error somehow? Only saying these ones because they might be used as a unique sign in thing. and i know it would be super unlikely that anything incorrect would happen but...thought we should make sure we can't have duplicates. Let's park this until I've deleted some test users though because I've got them all with my email address 🎃 here's a pumpkin

**Comment by xsd08tfu** [comment]
Theres not a lot we can do about this I think, because they aren't
duplicates. Maybe we add in a confirmation step like the "Hey Test is that
you?" but I'm not sure what we can do to prevent stupidity.

**Comment by hxc08vwu** [comment]
Just to clarify, I meant on the edit worker screen
