### ISSUE TITLE
Weird message when you clear filter

### ISSUE THREAD

**Issue by hxc08vwu** [xsd08tfu/sw-bug-tracker#143]
## Describe the bug ## 
Are you guys aware that on the real site it says this when you click "clear filter"

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND `event_finished` = 0 ORDER BY `event_date` ASC' at line 1

**Comment by xsd08tfu** [comment]
Is this on Test?

**Comment by xsd08tfu** [comment]
I bet there is a bracket introduced by the changes we made the other day!
