### ISSUE TITLE
Slow loading lists

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#148]
## Describe the bug ##
When trying to view the current worker list and inactive worker list, my browser is taking a while to show who's on there. I'm not sure if it's just mine but seems to be taking around 4 seconds which is just a bit longer than what it is usually.
**To Reproduce**

## Expected behavior ##

**Screenshots**

**Comment by xsd08tfu** [comment]
Can you try this on Test?

**Comment by hxc08vwu** [comment]
Inactive is being slow. Current loaded quite quickly. Hope this helps!



Caroline Stewart
Recruitment Events Officer

Recruitment and Outreach
Admissions, Recruitment and Marketing
Lawrence Stenhouse Building 0.20
University of East Anglia, Norwich Research Park, Norwich, NR4 7TJ
Tel: 01603 591762
Email: Caroline.Stewart@uea.ac.uk<mailto:Caroline.Stewart@uea.ac.uk>

[cid:image001.png@01D09851.EF67E200]

Gold (Teaching Excellence Framework 2017-2020)
UK Top 15 (The Times/Sunday Times 2019 and Complete University Guide 2019)
World Top 200 (Times Higher Education World University Rankings 2019)

[TEF Gold logo RGB]  [facebook] <http://www.facebook.com/ueaofficial>   [twitter-old] <http://www.twitter.com/uniofeastanglia>  [tumblr] <http://uniofeastanglia.tumblr.com/>  [flickr] <http://www.flickr.com/uniofeastanglia>  [linkedin] <http://www.linkedin.com/edu/school?id=12699>  [youtube] <http://www.youtube.com/ueaofficial>  [cid:image008.png@01CF8BB5.50024060] <http://instagram.com/uniofeastanglia>

This email is confidential and may be privileged. If you are not the intended recipient please accept my apologies; please do not disclose, copy or distribute information in this email or take any action in reliance on its contents: to do so is strictly prohibited and may be unlawful. Please inform me that this message has gone astray before deleting it. Thank you for your co-operation.
Any personal data exchanged as part of this email conversation will be processed by the University in accordance with current UK data protection law and in line with the relevant UEA Privacy Notice

**Comment by hxc08vwu** [comment]
Like inactive is still loading…



Caroline Stewart
Recruitment Events Officer

Recruitment and Outreach
Admissions, Recruitment and Marketing
Lawrence Stenhouse Building 0.20
University of East Anglia, Norwich Research Park, Norwich, NR4 7TJ
Tel: 01603 591762
Email: Caroline.Stewart@uea.ac.uk<mailto:Caroline.Stewart@uea.ac.uk>

[cid:image001.png@01D09851.EF67E200]

Gold (Teaching Excellence Framework 2017-2020)
UK Top 15 (The Times/Sunday Times 2019 and Complete University Guide 2019)
World Top 200 (Times Higher Education World University Rankings 2019)

[TEF Gold logo RGB]  [facebook] <http://www.facebook.com/ueaofficial>   [twitter-old] <http://www.twitter.com/uniofeastanglia>  [tumblr] <http://uniofeastanglia.tumblr.com/>  [flickr] <http://www.flickr.com/uniofeastanglia>  [linkedin] <http://www.linkedin.com/edu/school?id=12699>  [youtube] <http://www.youtube.com/ueaofficial>  [cid:image008.png@01CF8BB5.50024060] <http://instagram.com/uniofeastanglia>

This email is confidential and may be privileged. If you are not the intended recipient please accept my apologies; please do not disclose, copy or distribute information in this email or take any action in reliance on its contents: to do so is strictly prohibited and may be unlawful. Please inform me that this message has gone astray before deleting it. Thank you for your co-operation.
Any personal data exchanged as part of this email conversation will be processed by the University in accordance with current UK data protection law and in line with the relevant UEA Privacy Notice

**Comment by xsd08tfu** [comment]
I think this is fixed on Test?

**Comment by mxk16sbu** [comment]
Yup, all sorted! Thanks!
