### ISSUE TITLE
Filters aren't working properly 

### ISSUE THREAD

**Issue by hxc08vwu** [xsd08tfu/sw-bug-tracker#157]
## Describe the bug ##
When you include two groups, it is basically going "loading" for AGES
It's fine with one group and loads properly.
I've trialled it with trying to filter with 2 schools and then with a school and a year of course...both pose the same problem.

**Comment by hxc08vwu** [comment]
Interestingly, when I go back into the filter box, the school has disappeared and "Y4" is the only group left in the "Included" box

**Comment by hxc08vwu** [comment]
And then when I'm trying to filter with 2 schools, and go back into the filter view after clicking "apply"...both schools have disappeared from the "Included" box.

**Comment by xsd08tfu** [comment]
xsd08tfu/digital-sign-in#146
