### ISSUE TITLE
remove .php

### ISSUE THREAD

**Issue by benjalon** [xsd08tfu/sw-bug-tracker#172]
Do you think at some point we should remove the .php from URLs. Maybe when students join?

**Comment by xsd08tfu** [comment]
As in move to a mod_rewrite? we could do...

**Comment by benjalon** [comment]
Yeah i think it's something like that. Obviously not urgent at all but might be nice further down the line.

**Comment by xsd08tfu** [comment]
I've been doing this with an API i have written and its really simple. I'll
give it a little implement on Test sometime and see what happens
