### ISSUE TITLE
Phone numbers for students during events

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#174]
## What feature are you looking for? ##
When looking at students who are still signed in on the event, could we click on the name and it appear with their phone number? We're always having to phone students at the end of the day so would be a really handy feature.

**Comment by xsd08tfu** [comment]
THanks Matt. Once we have workers as objects this will be really easy to achieve!

**Comment by xsd08tfu** [comment]
Fixed with xsd08tfu/digital-sign-in#155
