### ISSUE TITLE
Add 'payroll' workflow to all new workers.

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#176]
## What feature are you looking for? ##
Add 'payroll' workflow to all new workers when they sign up to the system. All need to do it anyway but can work without that being completed.

**Comment by hxc08vwu** [comment]
I believe this is something we’re planning on making and is in V16 or V17 anyway…so once the right to work is completed, it will automatically assign payroll workflow. Is this what you mean Matt?



Caroline Stewart
Recruitment Events Officer

Recruitment and Outreach
Admissions, Recruitment and Marketing
Lawrence Stenhouse Building 0.20
University of East Anglia, Norwich Research Park, Norwich, NR4 7TJ
Tel: 01603 591762
Email: Caroline.Stewart@uea.ac.uk<mailto:Caroline.Stewart@uea.ac.uk>

[cid:image001.png@01D09851.EF67E200]

Gold (Teaching Excellence Framework 2017-2020)
UK Top 15 (The Times/Sunday Times 2019 and Complete University Guide 2019)
World Top 200 (Times Higher Education World University Rankings 2019)

[TEF Gold logo RGB]  [facebook] <http://www.facebook.com/ueaofficial>   [twitter-old] <http://www.twitter.com/uniofeastanglia>  [tumblr] <http://uniofeastanglia.tumblr.com/>  [flickr] <http://www.flickr.com/uniofeastanglia>  [linkedin] <http://www.linkedin.com/edu/school?id=12699>  [youtube] <http://www.youtube.com/ueaofficial>  [cid:image008.png@01CF8BB5.50024060] <http://instagram.com/uniofeastanglia>

This email is confidential and may be privileged. If you are not the intended recipient please accept my apologies; please do not disclose, copy or distribute information in this email or take any action in reliance on its contents: to do so is strictly prohibited and may be unlawful. Please inform me that this message has gone astray before deleting it. Thank you for your co-operation.
Any personal data exchanged as part of this email conversation will be processed by the University in accordance with current UK data protection law and in line with the relevant UEA Privacy Notice

**Comment by xsd08tfu** [comment]
Done! Caroline will catch up with you about how we do this sort of thing so you can do it in the future 🚀
