### ISSUE TITLE
Table of tables

### ISSUE THREAD

**Issue by xsd08tfu** [xsd08tfu/sw-bug-tracker#179]
- [ ] Columns
   - Table name
   - Col name
   - Col desc
   - Col default vis
   - Col sort
   - Col display

**Comment by xsd08tfu** [comment]
Again, I can't remember the real benefit of doing this? @benjalon any thoughts?

**Comment by benjalon** [comment]
Was it to keep user's preferences? I'm sure if we need it we'll probably come up with it again
