### ISSUE TITLE
student guide email address

### ISSUE THREAD

**Issue by hxc08vwu** [xsd08tfu/sw-bug-tracker#180]
## Describe the bug ##
By chance I could see that there was an email in the old student guides inbox about putting in details wrong on the system (they were like "sorry, I put in my mobile wrong")...so, I was wondering, is there anywhere on the system where it says "contact student.guides@uea.ac.uk if there are any problems.

If there is, we need to make sure that the new email address recruitment.reps@uea.ac.uk

**Comment by xsd08tfu** [comment]
This should of course be a global setting.... @Ben Longhurst (Benjalon)
<benjalon@gmail.com>
