### ISSUE TITLE
Duplicates in generated timesheets

### ISSUE THREAD

**Issue by Hayley9612** [xsd08tfu/sw-bug-tracker#181]
## Describe the bug ##
On the 16 Feb applicant day and 22 Feb applicant day generated timesheets there are duplicates of each entry listed
2 x every entry on the 16th
multiple duplicates on the 22nd February

**To Reproduce**

This can be seen by looking at finalised events timesheets

## Expected behavior ##
No duplicates :)
**Screenshots**
I have a screen shot however you can see these by clicking on the finalised timesheets using dates above - the 22nd looks particularly interesting!

**Comment by xsd08tfu** [comment]
Hi @Hayley9612. I've fixed this. Looks like the button to Generate Timesheet was pressed multiple times, it can be a bit slow with this many records, so we can make the button change to a loading icon or something to show progress.

We've removed the duplicates for both those events, and prevented it happening again 👍
