### ISSUE TITLE
Student stuck in inactive worker

### ISSUE THREAD

**Issue by Hayley9612** [xsd08tfu/sw-bug-tracker#184]
## Describe the bug ##

Natalie Wood 100112334 seems to be stuck in the inactive worker section - workflows have been completed, she has a current payroll number and has contract dates filled in but doesn't seem to migrate across to current workers. Are we able to transfer her across?

**To Reproduce**

## Expected behavior ##

**Screenshots**

**Comment by xsd08tfu** [comment]
This seems to have fixed itself!
