### ISSUE TITLE
Finalise Event Notification 

### ISSUE THREAD

**Issue by amylhumphreys** [xsd08tfu/sw-bug-tracker#204]
## Describe the bug ##
When clicking through notification link it brings up an error screen. 

Error appears as:

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND `user_team` != 0' at line 1 Query: SELECT * FROM studentw_users.`global-users` WHERE `user_id` = AND `user_team` != 0

**To Reproduce**
1. Select notification list
2. Click notification to finalise event

**Screenshots**
![Error1](https://user-images.githubusercontent.com/49563477/58635116-eead4d00-82e4-11e9-920b-d3974927a5cb.PNG)

![Error2](https://user-images.githubusercontent.com/49563477/58635129-f79e1e80-82e4-11e9-8592-35d03275be8a.PNG)

**Comment by benjalon** [comment]
Note for later: 
- Could be because it has been finalised (unless it wasn't until that was clicked). 
- I just had this on my branch and it was because it was trying to construct a user but there was a blank entry in one of the fields for the event in the db.
