### ISSUE TITLE
Student appearing as current

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#209]
## Describe the bug ##
We just had a student 'Poppy Harvey' email us to say she didn't attend training etc but has been getting jobs through on the system. She didn't have any complete workflows so I'm sure how she ended up in the current list. I've removed her scheme now but not sure if there's been some sort of bug? Or whether she was added ages ago. I was going to ask Hayley (as she's a MED student) but not in until Monday so thought I'd log it just in case!

**To Reproduce**

## Expected behavior ##

**Screenshots**

**Comment by xsd08tfu** [comment]
Thanks for this Matt. I think this may have been user error, but keep your eyes out for any more and I can look in to it more
