### ISSUE TITLE
Worker Reactivation

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#219]
## Describe the bug ##
Trying to move worker back to future/current after being in past. Worker reactivation workflow doesn't seem to be working.
**To Reproduce**

## Expected behavior ##

**Screenshots**

**Comment by kqq17rqu** [comment]
Worker Reactivation seems to work for some people and not others. 
Alejandra Hart (past worker) - worker reactivation won't work 
Eve Hitchens (past worker) - worker reactivation won't work 
Tara Hall - Worker Reactivation worked
