### ISSUE TITLE
Error loading tables

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#226]
## Describe the bug ##
![1](https://user-images.githubusercontent.com/40841396/67281488-6d3e9d00-f4c7-11e9-989e-36076787fe6d.PNG)

**To Reproduce**

## Expected behavior ##

**Screenshots**

**Comment by xsd08tfu** [comment]
Hi Matt,

Thanks for this. Can you try it again for me? If it still happens, can you
open the Inspector on chrome, then go to resources. Reload the page and one
should be highlighted red. Can you tell me what it says when you click on
it?

**Comment by xsd08tfu** [comment]
I would also add that this isn't happening on live, only on test!
