### ISSUE TITLE
Schools shown on allocation page

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#229]
## What feature are you looking for? ##
When allocating for a job, it would be really useful to have the school of the student show up on the table. It would also be great if we could click on the student name and show information like the groups they're in without ticking them?

**Comment by xsd08tfu** [comment]
Hi Matt, I'll add the school in. Bit harder to avoid the ticking them bit but will work on it.

**Comment by xsd08tfu** [comment]
Same as #227
