### ISSUE TITLE
Future workers seeing jobs

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#231]
## Describe the bug ##
We're getting future workers booking on to events even though they shouldn't be able to see it. For example, Stephan Mitch Kwo Tseng Vi, who was in future had been allocated to the Mini Open Day and has worked.
**To Reproduce**

## Expected behavior ##

**Screenshots**

**Comment by xsd08tfu** [comment]
Ok this should be fixed. You may get a few future workers saying they can't log in in the interim but this will change again in a future version.
