### ISSUE TITLE
Accommodation reps - cancellations

### ISSUE THREAD

**Issue by Hayley9612** [xsd08tfu/sw-bug-tracker#233]
Just thinking ahead - if an accom rep cancels their shift the system automatically will allocate a replacement - this isn't going to be as helpful for accommodation reps as we book them based on the flat they they represent and we would want to replace like for like

## Describe the bug ##

**To Reproduce**

## Expected behavior ##

**Screenshots**

**Comment by xsd08tfu** [comment]
Right... yes see this problem! I will work on a fix and test for accommodation reps jobs.
