### ISSUE TITLE
Need to add validation to event adding 

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#241]
## Describe the bug ##
Just created an event for Boston College campus visit twice today but it won't appear in the event list. Any new event doesn't seem to be saving?
**To Reproduce**

## Expected behavior ##

**Screenshots**

**Comment by xsd08tfu** [comment]
Hi Matt,

I've looked in to this and it's because you saved them as 08/01/2019....
not 08/01/2020, so they are there, just not where you expect them to be as
that was almost a year ago.... dates changed!

**Comment by mxk16sbu** [comment]
Ah bugger, it was a long day … cheers!!

Kind Regards

Matt Knightley
Recruitment Events
SCI 3.17

Admissions, Recruitment and Marketing Department
University of East Anglia, Norwich Research Park, Norwich, NR4 7TJ
Tel: +44 (0)1603 593704
Email: m.knightley@uea.ac.uk<mailto:m.knightley@uea.ac.uk>

University of East Anglia, Norwich Research Park, Norwich, NR4 7TJ
Tel: 01603 593704

[cid:image001.png@01D09851.EF67E200]

Gold (Teaching Excellence Framework 2017-2021)
World Top 200 (Times Higher Education World University Rankings 2020)
UK Top 25 (The Times/Sunday Times 2020 and Complete University Guide 2020)
World Top 50 for research citations (Times Higher Education World University Rankings 2020)

[TEF Gold logo RGB]<http://www.hefce.ac.uk/tefoutcomes/#/provider/10007789> [facebook] <http://www.facebook.com/ueaofficial>  [twitter-old] <http://www.twitter.com/uniofeastanglia>  [tumblr] <http://uniofeastanglia.tumblr.com/>  [flickr] <http://www.flickr.com/uniofeastanglia>  [linkedin] <http://www.linkedin.com/edu/school?id=12699>  [youtube] <http://www.youtube.com/ueaofficial>  [cid:image008.png@01CF8BB5.50024060] <http://instagram.com/uniofeastanglia>

This email is confidential and may be privileged. If you are not the intended recipient please accept my apologies; please do not disclose, copy or distribute information in this email or take any action in reliance on its contents: to do so is strictly prohibited and may be unlawful. Please inform me that this message has gone astray before deleting it. Thank you for your co-operation.
