### ISSUE TITLE
Alessia Tarantino - Unable to login

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#243]
## Describe the bug ##
Not quite sure what's going on but this student says they've reset their password multiple times and cannot login. We've checked the username but can't figure out why.
**To Reproduce**

## Expected behavior ##

**Screenshots**

**Comment by xsd08tfu** [comment]
Hi Matt,

Ive looked in to this and can't replicate it! Can you ask them to try again
with their rest password?

**Comment by mxk16sbu** [comment]
No problem, emailed her and sent another password reset.

Thanks!

Kind Regards

Matt Knightley
Recruitment Events
SCI 3.17

Admissions, Recruitment and Marketing Department
University of East Anglia, Norwich Research Park, Norwich, NR4 7TJ
Tel: +44 (0)1603 593704
Email: m.knightley@uea.ac.uk<mailto:m.knightley@uea.ac.uk>

University of East Anglia, Norwich Research Park, Norwich, NR4 7TJ
Tel: 01603 593704

[cid:image001.png@01D09851.EF67E200]

Gold (Teaching Excellence Framework 2017-2021)
World Top 200 (Times Higher Education World University Rankings 2020)
UK Top 25 (The Times/Sunday Times 2020 and Complete University Guide 2020)
World Top 50 for research citations (Times Higher Education World University Rankings 2020)

[TEF Gold logo RGB]<http://www.hefce.ac.uk/tefoutcomes/#/provider/10007789> [facebook] <http://www.facebook.com/ueaofficial>  [twitter-old] <http://www.twitter.com/uniofeastanglia>  [tumblr] <http://uniofeastanglia.tumblr.com/>  [flickr] <http://www.flickr.com/uniofeastanglia>  [linkedin] <http://www.linkedin.com/edu/school?id=12699>  [youtube] <http://www.youtube.com/ueaofficial>  [cid:image008.png@01CF8BB5.50024060] <http://instagram.com/uniofeastanglia>

This email is confidential and may be privileged. If you are not the intended recipient please accept my apologies; please do not disclose, copy or distribute information in this email or take any action in reliance on its contents: to do so is strictly prohibited and may be unlawful. Please inform me that this message has gone astray before deleting it. Thank you for your co-operation.
