### ISSUE TITLE
After approving event, can't generate timesheet

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#244]
## Describe the bug ##
For the school campus visit on the 8th, vicki approved the costs and then when I go to generate the timesheet, it only lets me download it with the student names and hours rather than including their payroll number etc.
**To Reproduce**

## Expected behavior ##

**Screenshots**

**Comment by xsd08tfu** [comment]
Hi Matt, show me this on Monday if you don't mind!

**Comment by xsd08tfu** [comment]
As discussed, this is expected behaviour now!
