### ISSUE TITLE
Sign in screen like st stephens gate

### ISSUE THREAD

**Issue by xsd08tfu** [xsd08tfu/sw-bug-tracker#35]
**What feature are you looking for?**
Students should be able to identify without revealing all details

**How should it work for the user?**
They should be presented with a screen to choose:
- First letter of First Name
- First letter of Last Name
- Day (date: eg 26) of Birth
- And another step or two if needed on demand.

**What would make this feature awesome?**
This to be faster than the old method

**What would make this feature a success?**
It to work nicely!

**Comment by benjalon** [comment]
- I've made this and it looks ok. Might need to edit the colours etc. 
- We'll probably need to talk about how it should be designed and how a few of the mechanics work. 
- It doesn't have any way to check for birthday as this isn't on the system so it works just for the initials so far and has a confirmation if a few records with the same initials are found.

**Comment by xsd08tfu** [comment]
I think we can use jQuery focus to speed up switching boxes

**Comment by xsd08tfu** [comment]
This needs to get Birthdays before it can go live.

**Comment by xsd08tfu** [comment]
Birthdays can be manually updated from eVision. I will identify those without a Birthday listed, and share a list to be updated.
