### ISSUE TITLE
Year of Study

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#36]
**What feature are you looking for?**
Current Year of Study
**How should it work for the user?**
Attribute for student worker
**What would make this feature awesome?**
Maybe in the future, once the new year begins, it could automatically update their year of study? It may be an issue in that most 3rd year students will graduate, whilst some won't be. Could the course they're linked to through their student worker profile have a set amount of year they're expected to study and it update via?
**What would make this feature a success?**
Including year of study and automatically updating each September. Dependent on course (3 year course etc), it could automatically stop increasing each year after they graduate.

**Comment by xsd08tfu** [comment]
This needs to have a link to the student records system to work.
