### ISSUE TITLE
Record of events worked

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#37]
**What feature are you looking for?**
Once someone has signed in to work, could the event be recorded on their student worker information?
**How should it work for the user?**
Record for student worker.
**What would make this feature awesome?**

**What would make this feature a success?**
Allowing us to keep track of what they worked on. Useful for references, performance issues etc

**Comment by xsd08tfu** [comment]
Hi @mxk16sbu 

This can be done once events are finalised, and you can view them by navigating to the list of workers, then clicking a student. I'm going to close this issue as I think it is already provided. If not, just shout!
