### ISSUE TITLE
Downloading Student Worker List

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#39]
**What feature are you looking for?**
Include student number in excel document when downloading from list of student workers
**How should it work for the user?**
Including student number in column
**What would make this feature awesome?**

**What would make this feature a success?**

**Comment by xsd08tfu** [comment]
Can we also look at customisable columns? The user can choose what they want in the view? maybe we could even store this in the session cookie!!!

**Comment by benjalon** [comment]
Maybe we should make the view customisation a separate issue. Would it be on all tables across the system or just the student worker list? Have sorted the student number request.

**Comment by xsd08tfu** [comment]
Agreed!
