### ISSUE TITLE
duplicate sign ins

### ISSUE THREAD

**Issue by xsd08tfu** [xsd08tfu/sw-bug-tracker#40]
Hi Ben,

We have had a bit of a problem at the open days with duplicate sign ins, in order to fix this can we implement these fixes:

- Hide the sign in form (just a simple Jquery slide up event on button press and slide down on success) as people press to sign in. You’ll find this in in_out.php, all the script is at the bottom.
- Stop people signing in in multiple times in a short space of time. Add in to the script a 5 minute cool off (so check for a time stamp, if they have one in the last 5 mins, return a success message saying they’ve already filled this form in in the last 5 mins, and we don’t submit another time stamp to the server.

Hope this is ok!

Myles

**Comment by benjalon** [comment]
I have submitted the code for this but I can't seem to put it in the 'in progress' or 'finished' sections of my project.
