### ISSUE TITLE
Strike System on profile

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#42]
**What feature are you looking for?**
A flag system on a student profile to highlight when there's been an issue.
**How should it work for the user?**
Be able to press a flag icon and type a description of the issue on the student profile
**What would make this feature awesome?**
Incorporating a "add strike" button which produces a flag and description on their profile
**What would make this feature a success?**
When viewing a profile for future work or references, it would immediately highlight that there has been an issue. Also, allow us to remove a strike in case of user error.

**Comment by xsd08tfu** [comment]
Before this can be coded, it needs to be worked out from a HR perspective as workers would have disciplinary actions recorded!

**Comment by mxk16sbu** [comment]
Could we possibly add a star system or something like that to indicate of good feedback also? Allowing us to make comments too? Dependent on HR's stance I guess
