### ISSUE TITLE
Remove password reset not by email!

### ISSUE THREAD

**Issue by xsd08tfu** [xsd08tfu/sw-bug-tracker#46]
Hi Ben, can you change the way we handle password resets where we dont email the user, i.e. stop displaying the token and URL, and just put in a message like password disabled.

Also can you come up with a SQL event to clear out old tokens after they've expired!

**Comment by benjalon** [comment]
When you say SQL event is that a bit of code I put in the PHP somewhere?

**Comment by benjalon** [comment]
Ah, if I'm working on a separate server will it actually affect the proper system?

**Comment by xsd08tfu** [comment]
Shouldn’t do! However if you can test it to see how it functions, then when I’m back next week we can work to apply what you did to the main server.

**Comment by benjalon** [comment]
Yep ok! I thought as much but just wanted to check.

**Comment by benjalon** [comment]
Just enter this code into the SQL section on the events_users db:

SET GLOBAL event_scheduler = ON

CREATE EVENT `remove_password_reset_tokens` 
ON SCHEDULE EVERY 1 DAY 
DO DELETE FROM `password-resets` WHERE reset_expiry < NOW()

**Comment by xsd08tfu** [comment]
Closing this as waiting on IT to confirm if we can have events access!
