### ISSUE TITLE
UK, EU or INT 

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#49]
**What feature are you looking for?**
Would be handy to allow us to select whether a student is UK, EU or an International student
**How should it work for the user?**
Have it as a category on their profile
**What would make this feature awesome?**

**What would make this feature a success?**
Being able to filter down using this. Sometimes we have specific requests for an international student for example so would be great.

**Comment by xsd08tfu** [comment]
@mxk16sbu @hxc08vwu You can now add these groups! Close once done!
