### ISSUE TITLE
Group adding

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#50]
**Describe the bug**

When adding group to a worker profile, some groups require one click and some two clicks.

**Comment by xsd08tfu** [comment]
Sorry for the accidental close!!!

**Comment by xsd08tfu** [comment]
Ok, so the issue here is around my poor JS. I quickly wrote to listen for clicks on each div seperately, so the first click activates the div for click events, the second activates the actual function. Should all be one click!!

**Comment by benjalon** [comment]
Additionally, if you click the div X times then click the button it adds X of the same group to the worker.
