### ISSUE TITLE
Edit Worker - Button Placement

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#51]
### I would make the shifts worked section collapsed (and expandable) as opposed to moving the button ~ Myles ###

**What feature are you looking for?**
Just moving the Edit Worker button up nearer the top when viewing a profile. As a student does more and more shifts, the button goes further down so would be nice to include above the shifts worked section.
**How should it work for the user?**
A little more accessible quickly.
**What would make this feature awesome?**

**What would make this feature a success?**

**Comment by xsd08tfu** [comment]
See comment above!
