### ISSUE TITLE
Incomplete worker field bugs

### ISSUE THREAD

**Issue by benjalon** [xsd08tfu/sw-bug-tracker#55]
If workers are created without all the fields completed e.g. no student number, then it causes an issue on the sign in page where any value input that doesn't register with the database defaults to a record with no student number. 

This could be fixed by forcing the user to enter all the values when creating a worker or a check in the sign in process.

**Comment by xsd08tfu** [comment]
Good catch!

I would suggest checking at the sign in stage, and requiring (we can use HTML5 validation) mobile number, email and student number. We should also make name required!!

**Comment by benjalon** [comment]
Note to self: This is part of the improved sign in branch.
