### ISSUE TITLE
Deleting duplicate worker entries

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#56]
**What feature are you looking for?**
Ability to delete a student worker
**How should it work for the user?**
Delete option in 'edit worker'
**What would make this feature awesome?**

**What would make this feature a success?**

**Comment by benjalon** [comment]
Could:
- have a rule in the database to prevent duplicate entries. 
- Add delete button to the workers page with a lot of confirmation just in case.
