### ISSUE TITLE
Removing time from contract start/end date

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#60]
**What feature are you looking for?**
Had a think about the specific time on the contract end date and think it's probably best with just the date. We generally don't need that much information.
**How should it work for the user?**
Just show a date rather than date and time
**What would make this feature awesome?**

**What would make this feature a success?**

**Comment by hxc08vwu** [comment]
**I think this can be done or hidden from view or something...but if it's not possible let me know and will remove it!**

**Comment by xsd08tfu** [comment]
fixed and merged!
