### ISSUE TITLE
Can't put it live!

### ISSUE THREAD

**Issue by xsd08tfu** [xsd08tfu/sw-bug-tracker#63]
Just realised I can't put the latest changes live yet as I don't know what changes have been made to the db. I know theres at least one change in the worker start date and a new table user_sessions. 

We will chat about this more on Monday, but just flagging!

Probably need to make an issue to write a DB set up and DB upgrade script for versions going forward...

**Comment by xsd08tfu** [comment]
I think we could do [this](https://stackoverflow.com/questions/5382437/what-is-the-best-way-to-create-a-php-mysql-upgrade-script-for-a-software-develop) to create an install/upgrade script?

**Comment by benjalon** [comment]
The sessions dB needs to be added. The only column I added other than that
table was the worker_contract_start.

But yeah we do need to have it automated. It doesn't look like it'd be too
hard if it is anything like that post. Could probably have it done in a few
hours on Monday.

**Comment by xsd08tfu** [comment]
Wonderful! Don’t worry about it over the weekend, I’m just trying to get
ahead of next week.
