### ISSUE TITLE
Prospects screen

### ISSUE THREAD

**Issue by hxc08vwu** [xsd08tfu/sw-bug-tracker#67]
**What feature are you looking for?**
We need a screen for prospective student workers when they register their interest 
**How should it work for the user?**
There should be a workflow to follow and several approval steps are needed by admins before we can accept a worker onto the system.
**What would make this feature awesome?**
We can discuss the specifics needed for each approval step at the next steering group
**What would make this feature a success?**

**Comment by hxc08vwu** [comment]
@benjalon @xsd08tfu ...do students need a log in to be able to do this? Or do they need a log in for signing up to shifts? What are your thoughts?

**Comment by xsd08tfu** [comment]
They would need a log in to sign up to shifts, but I don't think they would need a log in to sign up as a prospect. We could generate them a URL (with a nice long unique token) to access their application and see progress?
