### ISSUE TITLE
Timesheet can show negative time

### ISSUE THREAD

**Issue by xsd08tfu** [xsd08tfu/sw-bug-tracker#70]
I just accidentally generated a timesheet with two timestamps the same, and it tried to pay a student for -0.01 hours. I think that will break Payroll.

**Comment by benjalon** [comment]
Additionally, sometimes when a timestamp is inserted it will count as an out despite the time on it. A list probably just needs sorting somewhere. 

<img width="1149" alt="screen shot 2018-08-13 at 16 08 34" src="https://user-images.githubusercontent.com/14875816/44040461-440b4074-9f13-11e8-9652-6cb11dc6d340.png">
