### ISSUE TITLE
Data field for first year accommodation info

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#77]
**What feature are you looking for?**
Ability to input their first year accommodation type e.g "Ensuite", "Standard" etc. Then also allow us to put in what specific accommodation they stayed in e.g "Hickling House", "Norfolk Terrace" etc.
**How should it work for the user?**

**What would make this feature awesome?**

**What would make this feature a success?**
Useful when we download all students and can sort them into accommodation whilst sorting tour allocations.

**Comment by xsd08tfu** [comment]
And school too!
