### ISSUE TITLE
No duplicates on shift sign up

### ISSUE THREAD

**Issue by hxc08vwu** [xsd08tfu/sw-bug-tracker#80]
**What feature are you looking for?**
We need a feature within students registering their interest for a shift to make sure they don't fill it in again
**How should it work for the user?**
The student should see a notification like "you've already said you can work this - we'll be in touch to confirm if you're booked soon" or something more snazzy along those lines

**Comment by xsd08tfu** [comment]
Nice, we can just do a check against their worker ID, as they would have to sign in to sign up!
