### ISSUE TITLE
Flagging Tier 4 hours to international students

### ISSUE THREAD

**Issue by hxc08vwu** [xsd08tfu/sw-bug-tracker#81]
- [x] Visa expiry date
  - [x] if completed they are Tier 4
- [x] sign in screen check hours worked in past 7 days
  - [x] warn if event duration is greater than hours remaining
  - [x] hours limit set by global variable
  - [x] notify event lead if a tier 4 goes over 19 hours
- [x] Worker modal (new_modal) needs to show Hours in last 7 days.

**What feature are you looking for?**
A process of warning tier 4 visa students if they are exceeding their working hours, as discussed with the international office.
**How should it work for the user?**
Unsure...Ben, use your creative genius :)
**What would make this feature awesome?**

**What would make this feature a success?**

**Comment by xsd08tfu** [comment]
Notifications for staff in v16, then open new issue for student home page

**Comment by xsd08tfu** [comment]
- Visa expiry date
  - if completed they are Tier 4
- sign in screen check hours worked in past 7 days
  - warn if event duration is greater than hours remaining
  - hours limit set by global variable
  - notify event lead if a tier 4 goes over 19 hours
- Worker modal (new_modal) needs to show Hours in last 7 days.
