### ISSUE TITLE
Linking with things like UEA Award

### ISSUE THREAD

**Issue by hxc08vwu** [xsd08tfu/sw-bug-tracker#84]
Not essential...
**What feature are you looking for?**
As per the scoping doc, would be nice to have UEA Award or any other achievements linked to the student's profile
**How should it work for the user?**
I'm unsure, it needs a team chat 
**What would make this feature awesome?**

**What would make this feature a success?**

**Comment by xsd08tfu** [comment]
Pick this up with careers
