### ISSUE TITLE
Welcome Talk group

### ISSUE THREAD

**Issue by hxc08vwu** [xsd08tfu/sw-bug-tracker#85]
**What feature are you looking for?**
The ability to see whether students have done welcome talks before
**How should it work for the user?**
It should be a group maybe
**What would make this feature awesome?**

**What would make this feature a success?**

**Comment by xsd08tfu** [comment]
Make it a group!

**Comment by hxc08vwu** [comment]
I will :)! Been reading through the scoping doc and saw this.
