### ISSUE TITLE
Study Abroad 

### ISSUE THREAD

**Issue by Hayley9612** [xsd08tfu/sw-bug-tracker#86]
**What feature are you looking for?**
Can we have a tick box or group that guides can allocate themselves to if they are a Study Abroad Student please?
**How should it work for the user?**
When filling in their profile on sign up - self identify if they are on a SA course
**What would make this feature awesome?**

**What would make this feature a success?**

**Comment by xsd08tfu** [comment]
This is part of prospects and will be closed when it is put live.
