### ISSUE TITLE
Tabbed groups view

### ISSUE THREAD

**Issue by xsd08tfu** [xsd08tfu/sw-bug-tracker#93]
## What feature are you looking for? ##
Tabs in the group selection screen (with parent groups)
## How should it work for the user? ##
The user should be able to assign groups to families so they can only see groups that are relevant to them, then these should be displayed with tabs at the top of group selections.

**Comment by benjalon** [comment]
This should have schools implemented as groups. When a worker is created they should have an entry for school in the worker-group-memberships col. This can then be filtered with the new filter.
